name: Post-merge dev version bump â¬†ï¸

on:
  push:
    branches: [main]

concurrency:
  group: bump-dev-version-${{ github.ref }}
  cancel-in-progress: true

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write

jobs:
  bump-dev-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    if: |
      !(contains(github.event.commits[0].message, '[skip version bump]') ||
        contains(github.event.head_commit.message, '[skip version bump]')
      )

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          # Value already defaults to true, but `persist-credentials` is
          # required to push new commits to the repository.
          persist-credentials: true

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install {desc} and {stringr}
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: desc

      - name: Bump dev version in DESCRIPTION ğŸ“œ
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: desc::desc_bump_version("dev", normalize = TRUE)
        shell: Rscript {0}

      - name: Update Date field ğŸ“…
        run: if (desc::desc_has_fields("Date")) desc::desc_set("Date", Sys.Date())
        shell: Rscript {0}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump dev version [skip-version-bump]"
          file_pattern: |
            DESCRIPTION
